/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=40: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMTelephonyManager;
interface nsIDOMMozVoicemail;

[scriptable, builtinclass, uuid(360256f9-4a94-4134-bc1c-df304ad009d7)]
interface nsIDOMNavigatorTelephony : nsISupports
{
  readonly attribute nsIDOMTelephonyManager mozTelephonyManager;

  readonly attribute nsIDOMMozVoicemail mozVoicemail;
};
